# Generated by Django 5.1.3 on 2024-12-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casther', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horarios',
        ),
    ]
